# site settings
title: Bot Jekyll Theme
name: Bot/Jekyll
footer: "Designed by Rob Moffat"
subtitle: Kite9 Ltd
email: rob@kite9.com
description: For various Symphony Websites
baseurl: "/" # the subpath of your site, e.g. /blog
include: ['_pages']
url: https://robmoffat.github.io/bot-jekyll-theme
author: Kite9 Ltd
city: London
country: UK
phone: "+447900_247_282"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/robmoffat
linkedin_url: https://www.linkedin.com/in/robmoffat/

# build settings
markdown: kramdown

sass:
  style: compressed

  
# Search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false